### ISSUE TITLE
Programmatically access path of field(s) with error(s)

### ISSUE THREAD

**Issue by repli2dev** [nette/schema#33]
I believe it is not so uncommon to use such library when validating API parameters which is inherently connected to reporting errors back to the caller.

In such situation it is not uncommon to provide path* within the request payload and nette/schema does that in way that is not directly usable to be passed back to the response as it is available only (as far as I investigated) to the exception message.

So it would be nice to be able to access the path programmatically.

* Error response in our company is a array of errors with each having path, error message and error code.

**Comment by dg** [comment]
Method `$e->getMessages()` returns array of all message strings and `$e->getMessageObjects()` return all messages as [Nette\Schema\Message](https://api.nette.org/3.1/Nette/Schema/Message.html) objects and there is `path` property.

**Comment by repli2dev** [comment]
Tested on `master` and it seems to work nice! Good job :-) Closing as this is suitable now for our purpose.
