### ISSUE TITLE
String to DateTime returns \Nette\Utils\Arrays error

### ISSUE THREAD

**Issue by davtk** [nette/schema#44]
### Bug Description
I am not sure, if I am using this right, but I am trying to convert input string to result DateTime object

### Steps To Reproduce
https://fiddle.nette.org/nette/#4f2cd78abf
    
    class Foo {
        public \DateTime $bar;
    }
    
    $processor = new \Nette\Schema\Processor;
    $processor->process(
        \Nette\Schema\Expect::structure([
            'bar' => \Nette\Schema\Expect::string()->castTo('DateTime')
        ])->castTo(Foo::class),
        [
            'bar' => '2021-01-01',
        ]
    );

Will result in the error:

    Nette\Utils\Arrays::toObject(): Argument #1 ($array) must be of type iterable, string given, called in ...../vendor/nette/schema/src/Schema/Elements/Base.php on line 174

### Expected Behavior
Input string will be successfully mapped to target class DateTime property.

**Comment by SeriousKen** [comment]
I just came across this and I think the way cast works isn't properly explained in the documentation. All it does is instantiate an object and then map an array to public properties. It also won't work with any type that has constructor arguments. I can't see any way to coerce a string to a DateTime object with this library - which would be extremely useful.
