### ISSUE TITLE
Description attribute - Nette schema as an object representation for XSD / JsonSchema / WADL / ... 

### ISSUE THREAD

**Issue by zeleznypa** [nette/schema#45]
It will useful to have a possibility to convert integration schemas (XSD, JsonSchema, WADL, ...) to Nette/Schema or back.

Because of that, it will be nice to have a possibility to setup, not just Expectations, but also description for the Structure or it parts

**Comment by dg** [comment]
If this is still the case, I'll ask you to implement it.
