### ISSUE TITLE
Support custom cast function

### ISSUE THREAD

**Issue by JesusTheHun** [nette/schema#52]
It would like to be able to cast a value using a callable.

```php
class Foo {
  public static function fromString($bar) {
    // some logic
  }
}

$schema = Expect::structure([
  'foo' => Expect::string()->castTo(fn ($v) => Foo::fromString($v));
  'foo2' => Expect::string()->castTo('Foo::fromString');
});
```
I'm willing to make a PR for this if you accept the feature to be integrated in the project.

**Comment by JanTvrdik** [comment]
The idea is good, but it would be better to use different method name, to more accurately describe the action, e.g. `transform` (that the name [used by Zod](https://github.com/colinhacks/zod#transform))
