### ISSUE TITLE
Adding new PHP Versions as experimental

### ISSUE THREAD

**Issue by ItsReddi** [nette/schema#60]
Hi,
i tried to start an early php 8.4 adoption but since i do not know where the tail will finally end, i stopped it.
The problem is that several nette packages are bound to a max php version.

To make changes independently i would suggest to add "experimental" support to the nette packages, this would it make easier to fix upcoming issues with php 7.4 or further php versions.

If something like in: https://github.com/ItsReddi/schema/pull/1/files (tests.yaml) would be available in all nette packages it is maybe easier for the community to fix upcoming issues.

**Comment by JanTvrdik** [comment]
You can run composer install with `--ignore-platform-req=php+` option. See https://github.com/composer/composer/pull/10318

**Comment by dg** [comment]
@JanTvrdik that's good, but unfortunately it doesn't work for me
