### ISSUE TITLE
Exception in ValidationException.php

### ISSUE THREAD

**Issue by NoNoNo** [nette/schema#61]
Version: latest

### Bug Description

Got a _warning_:

> Undefined array key `0`

plus _error_:

> Call to a member function `toString()` on `null`

in

https://github.com/nette/schema/blob/b345035d253eef30e0e1438faf2b463b051983e0/src/Schema/ValidationException.php#L29

### Steps To Reproduce

Sorry, I don’t know what caused that.

**Comment by dg** [comment]
Without the ability to reproduce the error, I cannot resolve it
