### ISSUE TITLE
Warnings produced by PHP 8.3.2

### ISSUE THREAD

**Issue by mysiar** [nette/schema#62]
Version: 1.2.5

### Bug Description
PHP 8.3.2
produces below warnings
Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/vendor/nette/schema/src/Schema/Helpers.php on line 19

Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/vendor/nette/utils/src/Utils/Reflection.php on line 18

Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/vendor/nette/utils/src/Utils/Validators.php on line 18

this is casued by @internal annotation in Schema/Helpers.php

### Steps To Reproduce
Use the package with PHP 8.3.2

### Expected Behavior
No warnings

### Possible Solution
remove @internal annotation

**Comment by dg** [comment]
fixed in nette/utils v4.0.4
