### ISSUE TITLE
Assert with custom message.

### ISSUE THREAD

**Issue by integer** [nette/schema#7]
When you have more asserts for one value it is difficult to find which assert failed.

Same issue if you have more complex logic in your assert. For example you asserts relations between two fields of structure. In this case you get error like this
 `Failed assertion #0 for option 'data › items › 0' with value object.` which is not so useful.

What do you think about this feature. May I prepare PR?

**Comment by dg** [comment]
How would you like to solve it?

**Comment by dg** [comment]
Merged
